### ISSUE TITLE
Add HackNights subdomain

### ISSUE THREAD

**Issue by mauriciabad** [hackupc/old-hackersatupc-landing#6]
We should include the contents of [Hack Nights Landing Page repo](https://github.com/hackupc/hack-nights-landing) to the subdomain [https://hacknights.hackersatupc.org](https://hacknights.hackersatupc.org).

_The landing page is not finished yet_, but we may try connect it to the main domain so it can be deployed fast.

**Comment by AlbertSuarez** [comment]
Closing this because we finally decide to move the HackNights landing to hacknights.dev
